branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: unimeet
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.5 (Puma)
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
